### ISSUE TITLE
Use `rclone --update copy` instead of `rclone sync`

### ISSUE THREAD

**Issue by jbecker44** [AmberELEC/AmberELEC#882]
In the backup and restore scripts, the rclone commands should use `rclone --update copy` instead of `rclone sync` (see here: https://github.com/AmberELEC/AmberELEC/blob/ee3120365fe7be45b56093ffdbc4f4cd0346081e/packages/amberelec/config/distribution/modules/cloud_backup.sh#L38 and here: https://github.com/AmberELEC/AmberELEC/blob/ee3120365fe7be45b56093ffdbc4f4cd0346081e/packages/amberelec/config/distribution/modules/cloud_restore.sh#L38 )

This change addresses 2 issues with the current implementation. The first is that `rclone sync` is potentially lossy (see the first **Important** note on the official documentation page for sync: https://rclone.org/commands/rclone_sync/ , as well as this specific suggestion to use "copy" over "sync" in the rclone forums: https://forum.rclone.org/t/rclone-copy-or-sync/2089/5 ).

The second issue this resolves is that by default, both "sync" and "copy" will overwrite destination files with source files any time the file hashes do not match _even if the destination file is newer_. The `--update` flag will _not_ copy files from the source if they would overwrite a newer file in the destination and so is more often the desired behavior (see the `--update` option on the rclone global flags official documentation: https://rclone.org/flags/ )

Thanks for your time and effort!

**Comment by dhwz** [comment]
I haven't really looked at this issue for a longer time. Are you still interested in this change, we may have added a better solution lately with Syncthing.
