### ISSUE TITLE
Volume Keys/Brightness Shortcut No Longer Work After Update from 351Elec to AmberElec on 351MP

### ISSUE THREAD

**Issue by xcjs** [AmberELEC/AmberELEC#885]
I updated from the last stable release of 351Elec to AmberElec 20220627.

**Comment by xcjs** [comment]
Some more information - I downgraded to the latest 351Elec release - both the volume buttons and display brightness shortcuts work again.

**Comment by dhwz** [comment]
I don't understand what's not working, the buttons seem to work fine also on latest release? Which buttons are you trying to use?

**Comment by xcjs** [comment]
> I don't understand what's not working, the buttons seem to work fine also on latest release? Which buttons are you trying to use?
> 
> Oh and there are 100 brightness steps so you may have to hold the button, our press it multiple times to see a difference on some used displays.

The volume buttons on the left side of the RG351 MP stopped functioning entirely for me after the upgrade.

The volume bar, despite being enabled, would not show up over the EmulationStation UI. There was no change in volume at all, even after 50+ presses.

Likewise, when holding R3 while pressing the volume buttons, there was no change in display brightness, even after a large number of presses.

This functionality was restored when I downgraded to the last build  of 351Elec.

**Comment by xcjs** [comment]
When I get some time this week, I'll install AmberELEC directly to an SD card and see if the issue persists.

**Comment by xcjs** [comment]
Installing directly to micro SD card seems to have worked.

It looks like either something went wrong during the update or there might be a bug in the update process.

**Comment by xcjs** [comment]
Ok, I broke the volume keys again.

It's possibly related to changing the theme or toggling another setting.

**Comment by xcjs** [comment]
@dhwz Is this possible to re-open this issue at some point? Is there any information I can provide to help with this issue?

**Comment by alexander-billings** [comment]
I am also having this issue. A fresh install or factory reset will temporarily fix it. I can SSH to the device and kill the volume.sense.sh process and I'm able to use the volume keys again until I restart the device.

I ran
`journalctl | grep volume`

and the output is attached.
`Oct 10 10:09:59 RG351MP systemd[1]: volume.service: Failed to get cgroup ID on cgroup /sys/fs/cgroup/unified/system.slice/volume.service, ignoring: Operation not supported
Oct 10 10:09:59 RG351MP systemd[1]: volume.service: Ignoring invalid environment assignment 'export DEBUG=yes': /etc/profile
Oct 10 10:09:59 RG351MP systemd[1]: volume.service: Ignoring invalid environment assignment 'if test "$PROGRESS"=yes; then': /etc/profile
Oct 10 10:10:01 RG351MP volume_sense.sh[431]: evtest: No such file or directory
Oct 10 10:10:01 RG351MP headphone_sense.sh[540]:   Capabilities: volume
Oct 10 10:10:04 RG351MP emustation-config[1053]:   Capabilities: volume`
