### ISSUE TITLE
Sound doesn't work on a RG315V on v20220627 Sanshiro Tower

### ISSUE THREAD

**Issue by gamertoons** [AmberELEC/AmberELEC#888]
### Describe the bug
Sound does not work on RG315V with the latest release version of Sanshiro. AmberELEC-RG351V.aarch64-20220627

I installed the previous release 351ELEC-RG351V.aarch64-20211122 afterwards and sound works great

### To Reproduce
1. Install AmberELEC-RG351V.aarch64-20220627 on a RG315V
2. There is no sound

### Expected behavior
Sound should work, but doesn't, Settings are default. Sound is not on mute. 

### Device (please complete the following information):

AmberELEC-RG351V.aarch64-20220627

### Additional context
None

**Comment by dhwz** [comment]
Sound works also on 351V, use Discord for support.
