### ISSUE TITLE
Volume Keys/Brightness Shortcut No Longer Work Consistently on 351MP

### ISSUE THREAD

**Issue by xcjs** [AmberELEC/AmberELEC#927]
The last release of AmberElec still does not work with the volume keys and brightness shortcuts consistently.

Sometimes they work after a boot or reboot. Other times I have to change the active theme once or twice to activate them.

This is the same issue as #885 , but since that issue remains closed, I've created a new one here.

**Comment by dhwz** [comment]
https://github.com/AmberELEC/AmberELEC/commit/55a6c9bab570590b21448ffba74fb8943a5e1215

**Comment by dhwz** [comment]
@xcjs can you please try the latest pre-release
