### ISSUE TITLE
For the RGB20s version RG351MP is it compatible?

### ISSUE THREAD

**Issue by lionomega** [AmberELEC/AmberELEC#941]
I'm sorry to put this here, but I've read on the internet that the OS of the RG351MP works for the RGB20s console and I don't know if it's true.

**Comment by dhwz** [comment]
It's boring in these devices that correct but it's not working properly because audio is different, and as we don't get hardware from powkiddy we don't support these device.

**Comment by lionomega** [comment]
Oh! Thanks.
