### ISSUE TITLE
Games partition is write protected after the last update

### ISSUE THREAD

**Issue by GorillaWarHead** [AmberELEC/AmberELEC#949]
after updating my rg351p to the last AmberELEC version, I tried to add some roms to games partition but i keep getting a prompt saying the disk is write protected 
![Screenshot 2023-02-04 045017](https://user-images.githubusercontent.com/19646615/216746493-b2920a82-d270-4d39-b062-221cd935a589.jpg)

**Comment by dhwz** [comment]
you probably corrupted your SD card
