### ISSUE TITLE
About Retroarch Language Switching

### ISSUE THREAD

**Issue by clondy999** [AmberELEC/AmberELEC#960]
The device I am using is 351V
The version used is: 98504482f319a8b50d31034bb4f352e7d8037c90
I added the retroarch language pack through SSH, which is Japanese and Traditional Chinese, and saved it to exit.
Entering retroarch again will result in a font error, displaying a chaotic font.

![39e977af41fbd724de152c480e0e02b](https://user-images.githubusercontent.com/73311186/232744715-4f1ef131-abfa-43ed-8351-6d91aaea5c3e.jpg)

**Comment by dhwz** [comment]
Wdym b you've added language pack?

**Comment by clondy999** [comment]
yes. I have added the language pack.
This bug can be reproduced 100%.
If English is pre-set and then Chinese is set, the display will be normal. Then save the configuration file of RetroArch and exit.
Entering RetroArch again causes this issue.

**Comment by dhwz** [comment]
Again I don't understand why you did add something, all languages are already included and your not using the latest release of AmberELEC.

**Comment by clondy999** [comment]
This has nothing to do with language packs!
If the default language is Chinese, entering RetroArch will cause this issue

**Comment by dhwz** [comment]
If it's still happening on the latest RetroArch version, then it's RetroArch's fault, sorry we can't do anything there.
So it's RetroArch which is saving wrong settings, you may need to report it there not to us.

**Comment by clondy999** [comment]
Okay.
I can only fix it from the encoding

**Comment by dhwz** [comment]
https://github.com/libretro/RetroArch/issues/12215

**Comment by clondy999** [comment]
Thank you.！

**Comment by clondy999** [comment]
resolved

**Comment by dhwz** [comment]
Can you tell what you did? Maybe we can add it to our docs?

**Comment by clondy999** [comment]
Certainly. I chose to change the theme of retroarch
I have tried the link method you provided, but adding RetroArch fonts to the path also fails

**Comment by clondy999** [comment]
There are no issues with the XML theme

**Comment by dhwz** [comment]
Ok thanks

**Comment by clondy999** [comment]
This is what I should do
