### ISSUE TITLE
Wolfenstein 3D won‘t sway on RG351V.

### ISSUE THREAD

**Issue by kangoroo82** [AmberELEC/AmberELEC#974]
in Wolfenstein 3D App you can start the game. It runs (ecwolf??). You can walk left, right, forward and backwards but you can‘t sway to left or right.

in Doom everything works great.

could you fix that? Thank you

## This is only for actual bugs that can be reproduced on multiple systems!  ##
 For Support visit us in our Discord
https://discord.com/invite/R9Er7hkRMe

### Getting started
Before opening an issue, check the release notes of the version that you are using and recent commits.  Be sure to fill out the template completely, accurately, and with as much detail as possible.  Issues without sufficient detail will be rejected and closed.

### Describe the bug

Turn left and right are not used in rg351v. so you can not turn like in doom.

Jy13 should be left
Jy14 should be right
So forward should be Jy11
And Backward should be Jy12

so you can move correctly.
I made it manually. Could you do this Setting in your standard keymapping for wolfenstein3d with rg351v

### Expected behavior
A clear and concise description of what you expected to happen. I want that you can walk like in doom. 

### Device (please complete the following information):
 - Version of AmberELEC that you are using
 - Actual beta and before on RG351V

**Comment by dhwz** [comment]
We don't predefine any button mapping for ecwolf, what you got is the default configuration of the emulator.
